print("Hola desde Vscode")
precio = input("Ingrese el precio del producto:")
cantidad = input("Ingrese la cantidad a comprar:")
total = int(precio) * int(cantidad)
print("El total a pagar es de {}".format(total))
